name: coolstore-on-dapr
containerEngine: docker

extensions:
- name: dapr
  log-level: debug
  config: appconfig
  components-path: "./components/local/"
# - name: zipkin
# - name: elastic
#   logPath: ./.logs

services:

# - name: redis
#   image: redis
#   bindings:
#   - port: 6379

- name: postgres
  image:  postgres
  env:
  - name: POSTGRES_PASSWORD
    value: "P@ssw0rd"
  bindings:
  - port: 5432
    connectionString: Server=${host};Port=${port};User Id=postgres;Password=${env:POSTGRES_PASSWORD};
  volumes:
    - target: /docker-entrypoint-initdb.d/tye_postgres_init.sql
      source: tye_postgres_init.sql

- name: webapigatewayapp
  project: src/dotnet/api-gateway/Gateway.csproj
  env:
    - Redis=localhost
    - OpenIdConnect__Authority=https://localhost:5001
    - ReverseProxy__Clusters__inventoryApiCluster__Destinations__destination1__Address=http://inventoryapp
    - ReverseProxy__Clusters__productCatalogApiCluster__Destinations__destination1__Address=http://productcatalogapp
    - ReverseProxy__Clusters__shoppingCartApiCluster__Destinations__destination1__Address=http://shoppingcartapp:5004
    - ReverseProxy__Clusters__saleApiCluster__Destinations__destination1__Address=http://saleapp
  bindings:
  - port: 5000

- name: identityapp
  project: src/dotnet/identity-server/IdentityServer.csproj
  bindings:
  - port: 5001
    protocol: https

- name: inventoryapp
  dockerFile: src/rust/docker/Dockerfile-inventory
  dockerFileContext: src/rust/
  env:
    - HOST=0.0.0.0
    - PORT=80
    - PG_USER=postgres
    - PG_PASSWORD=P@ssw0rd
    - PG_DATABASE=inv_db
    - PG_HOST=host.docker.internal
    - PG_PORT=5432
    - RUST_LOG="sqlx::query=error,tower_http=debug,info"
    - RUST_BACKTRACE=1
  bindings:
    - port: 5002
      containerPort: 80
      protocol: http

- name: productcatalogapp
  dockerFile: src/rust/docker/Dockerfile-product-catalog
  dockerFileContext: src/rust/
  env:
    - HOST=0.0.0.0
    - PORT=80
    - PG_USER=postgres
    - PG_PASSWORD=P@ssw0rd
    - PG_DATABASE=cat_db
    - PG_HOST=host.docker.internal
    - PG_PORT=5432
    - RUST_LOG="sqlx::query=error,tower_http=debug,info"
    - RUST_BACKTRACE=1
  bindings:
    - port: 5003
      containerPort: 80
      protocol: http

- name: shoppingcartapp
  project: src/dotnet/shopping-cart/ShoppingCart.csproj
  bindings:
  - port: 5004

- name: saleapp
  dockerFile: src/go/docker/Dockerfile-sale
  dockerFileContext: src/go/
  bindings:
    - port: 5005
      containerPort: 80
      protocol: http
